// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhiwelwU1KlevYt0bvEeKy5LV3F-A7R-M',
    appId: '1:13155304073:web:0d1f8917cf657eb5b0fc58',
    messagingSenderId: '13155304073',
    projectId: 'senior-chat-73113',
    authDomain: 'senior-chat-73113.firebaseapp.com',
    databaseURL: 'https://senior-chat-73113-default-rtdb.firebaseio.com',
    storageBucket: 'senior-chat-73113.appspot.com',
    measurementId: 'G-BZGY7QNP2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmq2XhysZWegK8l6DTucVbzMPSR02B8uY',
    appId: '1:13155304073:android:2ef70b6712fb6c34b0fc58',
    messagingSenderId: '13155304073',
    projectId: 'senior-chat-73113',
    databaseURL: 'https://senior-chat-73113-default-rtdb.firebaseio.com',
    storageBucket: 'senior-chat-73113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7tN0nJ0iEP8-Tafxqz0m6Z9QTWJgyN_8',
    appId: '1:13155304073:ios:570d271d1db60ad9b0fc58',
    messagingSenderId: '13155304073',
    projectId: 'senior-chat-73113',
    databaseURL: 'https://senior-chat-73113-default-rtdb.firebaseio.com',
    storageBucket: 'senior-chat-73113.appspot.com',
    iosClientId: '13155304073-7pq0cj0026dmiga2qhnqfn1ts6r9eo92.apps.googleusercontent.com',
    iosBundleId: 'com.example.senior',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7tN0nJ0iEP8-Tafxqz0m6Z9QTWJgyN_8',
    appId: '1:13155304073:ios:570d271d1db60ad9b0fc58',
    messagingSenderId: '13155304073',
    projectId: 'senior-chat-73113',
    databaseURL: 'https://senior-chat-73113-default-rtdb.firebaseio.com',
    storageBucket: 'senior-chat-73113.appspot.com',
    iosClientId: '13155304073-7pq0cj0026dmiga2qhnqfn1ts6r9eo92.apps.googleusercontent.com',
    iosBundleId: 'com.example.senior',
  );
}
